aliases = {
    'koopakev' : 'Kevin, who loves women,',
    'FlyinFunk' : 'Sammy, the throat goat,',
    'kamendo' : 'My father',
    'tonto' : 'Low Tier God Enjoyer',
    'Shiba42x' : 'Josh\'s stupid ass',
    'Chief Ponce' : 'Andrew',
    'zjepson' : 'Zac',
    'willloveslakers' : 'Squilliam William Aw-Billiam',
    'Pun_Dorry' : 'Loot Goblin',
    'EstebanCeja' : 'Esteban',
    'art' : 'Sarah Jay enjoyer',
    'BigStinky' : 'Steve, of all fucking people',
    'Crymacho' : 'Alex, who hates women,',
    'WTFSomebodyActually' : 'Banjo Blast Barvy',
    'Chon Wang' : 'Kuya boy',
    'Chankles' : 'Charles',
    'Scuzi' : 'Scooter',
    'jedipoop' : 'Jedi Poop'
}